name: Docker Image CI

on:
  push:
    branches: [ "testing" ]
  # pull_request:
  #   branches: [ "master" ]
    paths:
      - [ '**.js', '**.html' ]  

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    #- name: Build the Docker image
      #run: docker build . --file Dockerfile --tag /hello-world:$(date +%s)
      #run: docker build . --file Dockerfile --tag rvlq/hello-world:${{ github.sha }}

    # Build and push
    - name: Publish to Registry
      uses: docker/build-push-action@v1
      with:
        repository: rvlq/hello-world
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tags: ${{ github.sha }}
        #path: 4-gitops/app
